# SC Hotline Compose: places a character generated by Gemini into the locked SC Shop Hotline set.
# The set is never altered: only the character is lifted from Gemini's picture, checked, scaled to the
# fixed head height and laid onto the exact set pixels, with the desk front always on top.
import base64, io
import numpy as np, cv2, requests
from PIL import Image
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()
_cache = {}

def load(url):
    if url in _cache: return _cache[url]
    im = np.array(Image.open(io.BytesIO(requests.get(url, timeout=60).content)).convert('RGB').resize((1080, 1920), Image.LANCZOS)).astype(np.float32)
    _cache[url] = im
    return im

def isblue(p): return (p[..., 2] > p[..., 0] + 35) & (p[..., 2] > p[..., 1] + 10)

class Req(BaseModel):
    set_url: str
    gen_b64: str
    desk_top: int = 1085
    front: int = 1135
    head_y: int = 470

@app.get('/health')
def health(): return {'ok': True}

@app.post('/hotline/compose')
def compose(r: Req):
    PA = load(r.set_url)
    Oo = np.array(Image.open(io.BytesIO(base64.b64decode(r.gen_b64))).convert('RGB').resize((1080, 1920), Image.LANCZOS)).astype(np.float32)
    side = np.zeros((1920, 1080), bool); side[340:r.desk_top - 10, 0:30] = True; side[r.front + 40:1700, :] = True
    Oo += PA[side].mean(axis=0) - Oo[side].mean(axis=0); np.clip(Oo, 0, 255, out=Oo)
    diff = np.sqrt(((Oo - PA) ** 2).sum(axis=2))
    moved = float(diff[side].mean())
    if moved > 14: return {'ok': False, 'reason': f'set moved ({moved:.1f})'}
    m = (diff > 38).astype(np.uint8) * 255
    m[:330] = 0; m[r.front + 30:] = 0; m[:, :100] = 0; m[:, 980:] = 0
    m = cv2.morphologyEx(m, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8)); m = cv2.morphologyEx(m, cv2.MORPH_CLOSE, np.ones((15, 15), np.uint8))
    n, lab, st, _ = cv2.connectedComponentsWithStats(m)
    if n < 2: return {'ok': False, 'reason': 'no character found'}
    m = np.where(lab == 1 + np.argmax(st[1:, cv2.CC_STAT_AREA]), 255, 0).astype(np.uint8)
    cnts, _ = cv2.findContours(m, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE); mf = np.zeros_like(m); cv2.drawContours(mf, cnts, -1, 255, -1)
    ys, xs = np.nonzero(mf); top = int(ys.min())
    if not (340 <= top <= 760): return {'ok': False, 'reason': f'head out of range ({top})'}
    if ys.max() < r.desk_top - 40: return {'ok': False, 'reason': 'not reaching the desk'}
    if len(ys) < 60000: return {'ok': False, 'reason': 'character too small'}
    if xs.min() < 110 or xs.max() > 970: return {'ok': False, 'reason': 'character too wide'}
    # extra objects: near-black, colourless areas inside the character outline beside his torso (a chair back, a stand)
    lum = Oo.mean(axis=2); chroma = Oo.max(axis=2) - Oo.min(axis=2)
    cx = int(xs.mean()); inside = mf > 0
    band = np.zeros_like(inside); band[r.desk_top - 260:r.desk_top, :] = True
    sides = band & inside & ((np.arange(1080)[None, :] < cx - 90) | (np.arange(1080)[None, :] > cx + 90))
    dark = sides & (lum < 60) & (chroma < 22)
    if dark.sum() > 2500: return {'ok': False, 'reason': f'extra object beside him ({int(dark.sum())} px)'}
    # scale about the desk line so every character's head top lands on the same line
    s = (r.desk_top - r.head_y) / max(1, (r.desk_top - top))
    M = np.float32([[s, 0, 540 * (1 - s)], [0, s, r.desk_top * (1 - s)]])
    L = cv2.warpAffine(Oo, M, (1080, 1920), flags=cv2.INTER_LANCZOS4)
    A = cv2.GaussianBlur(cv2.warpAffine(mf.astype(np.float32), M, (1080, 1920)), (5, 5), 0) / 255
    # the sign and the palm are never touched
    prot = np.zeros((1920, 1080), np.uint8)
    prot[380:720, 0:360] = (~isblue(PA[380:720, 0:360])).astype(np.uint8)
    prot[330:r.desk_top, 640:1080] = (~isblue(PA[330:r.desk_top, 640:1080])).astype(np.uint8)
    prot = cv2.dilate(prot, np.ones((9, 9), np.uint8)).astype(np.float32)
    A = A * (1 - prot)
    comp = PA * (1 - A[..., None]) + L * A[..., None]
    comp[r.front:] = PA[r.front:]
    out = io.BytesIO(); Image.fromarray(comp.clip(0, 255).astype(np.uint8)).save(out, 'PNG')
    return {'ok': True, 'scale': round(float(s), 3), 'png_b64': base64.b64encode(out.getvalue()).decode()}
